version: '3.7'

services:

  redis:
    image: "redis:alpine"
    command: redis-server
    ports:
     - 6379:6379

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8001 
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/order_book_db
      - DB_NAME=order_book_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - SECRET_KEY=jhFSKFHKUY&*(*@UFW)
    depends_on:
      - db
      - redis

  db:
      build:
        context: './backend/db'
        dockerfile: Dockerfile
      ports: 
        - 5435:5432
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
        - REACT_APP_WEBSOCKET_URL=${REACT_APP_WEBSOCKET_URL}
        - REACT_APP_WEB_SERVICE_URL=${REACT_APP_WEB_SERVICE_URL}
    ports:
      - 3007:80
    depends_on:
      - backend

  nginx:
    build:
      context: './nginx'
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend